apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-mongo-sm
  labels:
    app: mongodb-service
spec:
  ports:
    - port: ${port}
      targetPort: ${targetport}
  selector:
    app: mongodb
  type: LoadBalancer
