server:
  port: 8090

spring:
  rabbitmq:
    host: ${rabbitmqhost}
    port: ${rabbitmqport}
    username: ${rabbitmqusername}
    password: ${rabbitmqpassword}
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/socialmediauth
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

myjwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}

myredis:
  host: localhost
  port: 6379

