server:
  port: 8091

spring:
  data:
    mongodb:
      host: ${mongodbhost}
      port: ${mongodbport}
      database: ${mongodbDB}
      username: ${mongodbusername}
      password: ${mongodbpassword}
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service

myjwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}

myredis:
  host: localhost
  port: 6379